# Generated by Django 4.2.6 on 2023-11-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_action_alter_habit_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_execution',
            field=models.DateField(blank=True, null=True, verbose_name='Последнее выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(verbose_name='Приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.TimeField(verbose_name='Время на выполнение'),
        ),
    ]
